### ISSUE TITLE
unzip -j destroys the folder structure.

### ISSUE THREAD

**Issue by OneOfOne** [jedireza/gimp-hidpi#1]
Using `unzip -j gimp-hidpi-master.zip -d ~/.gimp-2.8/themes/gimp-hidpi/` removes the folder structure and puts everything in the same folder, which breaks the theme.

Should be `unzip gimp-hidpi-master.zip -d ~/.gimp-2.8/themes/gimp-hidpi/` (without the `-j`).

**Comment by jedireza** [comment]
Thanks for creating an issue. Would you be willing to create a PR for this?

**Comment by OneOfOne** [comment]
@jedireza done and great work btw!
