### ISSUE TITLE
It still looks tiny on my XPS 15 9560 (15" UHD screen)

### ISSUE THREAD

**Issue by chrisoffner3d** [jedireza/gimp-hidpi#11]
The theme unfortunately still makes the Gimp UI look tiny on my DELL XPS 15 9560's 15" UHD screen.

![tinygimp](https://user-images.githubusercontent.com/18167754/28385528-b3726254-6cc8-11e7-8759-661ef9cb04f4.jpg)

**Comment by jedireza** [comment]
Yeah the UI still doesn't scale. This theme mainly helps with the tool icons.
