### ISSUE TITLE
Not working in 2.8.18

### ISSUE THREAD

**Issue by tomdav999** [jedireza/gimp-hidpi#5]
Hi, I downloaded the latest version of Gimp (2.8.18).  I have a high DPI display and the icons are too small to decipher so I did some googling and found this repository.  Unfortunately it doesn't seem to be working.   I am 99.9% sure I downloaded the icons to the correct folder as I was able to download use the sv32 icon theme with 2.8.18.  However the sv32 theme is too small (albeit better than the stock icons).  Is this working?  Do these icons display larger than the sv32 theme?

**Comment by kiwiwings** [comment]
I had the same problem - the reason was that I've unpacked it into the wrong directory, so instead of `~/.gimp-2.8/themes/gimp-hidpi/gimp-hidpi-master` move the files one directory up to `~/.gimp-2.8/themes/gimp-hidpi`

As the icons were still to small for my display, I've made them larger, execute the following in the images subdirectory:

``` Shell
sed -i "s/\(height\|width\)=\\\"32\\\"/\\1=\"64\"/; 0,/transform=\\\"/s//transform=\"scale(2 2) /" *.svg
```

**Comment by LinuxOnTheDesktop** [comment]
For some Linux installations of GIMP - I do not know quite which - the relevant directory is within, not the root of `~`, but `~/.config/GIMP`. (Also, do we really need two command-line operations to install theme? Why not, that is, directly unzip to the final directory?)

@kiwiwings : thanks for the tip on extra scaling. Perhaps that tip should go in the README. Also, though: even after implementing the tip, some elements, such as the colours icons and various check-boxes-and-their-tips, remained too small (on my Framework 13-AMD, which uses DPI x 2). Perhaps the `sed` does not scale _all_ UI elements. I add: it boggles that GIMP, which is one of Linux's main graphics programs, does not have decent inbuilt hiDPI support.
