### ISSUE TITLE
Not really helping on 4k display

### ISSUE THREAD

**Issue by davide-romanini** [jedireza/gimp-hidpi#6]
I tried it on Linux Mint Cinnamon 18, gimp 2.8.16, with my 4k monitor at 3840x2160 resolution. Icons are still too small but the worst thing is that gui controls are not scaled at all. I googled a bit but didn't find any workaround solution. Am I missing something?

**Comment by jedireza** [comment]
Yeah I've never tested a 4k display. In the readme I mention (Macbook Pro Retina / X1 Carbon), which is what I lightly tested with.

Also from the readme:

> In summary, I just replaced the icons with flat-style SVGs and changed the background color.

So yeah the GUI controls are still bad.

**Comment by psi-4ward** [comment]
https://raw.githubusercontent.com/brion/gimp/0ddbf9b3732e11a5e7033418c17732295183a885/themes/HiDPI/gtkrc

**Comment by vgjenks** [comment]
> https://raw.githubusercontent.com/brion/gimp/0ddbf9b3732e11a5e7033418c17732295183a885/themes/HiDPI/gtkrc

A little explanation would be helpful. Where does this go?
