### ISSUE TITLE
not working on 3200x1800 resolution, gimp 2.8.x ubuntu 16.04

### ISSUE THREAD

**Issue by ghost** [jedireza/gimp-hidpi#8]
I just got a new laptop and tried out your theme and it seemed to change the icon sizes by about a pixel. I'm not sure what resolutions you have designed this for and which ones you have tested on.

**Comment by jedireza** [comment]
> I'm not sure what resolutions you have designed this for and which ones you have tested on.

I tested on a Macbook Pro Retina and an X1 Carbon.

If you figure out what the issue is please update this issue and if possible, open a PR with the fix.

**Comment by ghost** [comment]
>I tested on a Macbook Pro Retina and an X1 Carbon.

What's the resolution of those?

Will re-open whenever I have time to try and fix it with a PR :+1:
