### ISSUE TITLE
Not working on Arch

### ISSUE THREAD

**Issue by parszab** [jedireza/gimp-hidpi#9]
Hi,
thanks for the enhancement! Unfortunately I couldn't make it work on Arch with Gimp 2.818:

![0x2e003d1](https://cloud.githubusercontent.com/assets/15095671/22630338/914f2eba-ebf8-11e6-8b97-8ec8fb1a2d6a.png)

The theme is listed and can be selected in the Themes section, but doesn't really do anything. Would appreciate some help if I misunderstood something.

Cheers,
Szabolcs

**Comment by jedireza** [comment]
Thanks for opening an issue. I'm using Arch too. Not sure if the desktop would make a difference but I'm using Gnome.

**Comment by jedireza** [comment]
Thanks for opening an issue. I'm using Arch too. Not sure if the desktop would make a difference but I'm using Gnome.

**Comment by parszab** [comment]
Not sure, I'm using fvwm, but I'm also running gnome apps, and GTK themes also work.

**Comment by LucidTaZ** [comment]
For what it's worth, it doesn't work here either. I'm using Ubuntu with Cinnamon. I put Cinnamon in HiDPI mode but did not make other changes. Loading this theme appears to change _something_, but it does not make anything bigger. Gimp version: 2.8.16.

**Comment by nwallace** [comment]
I'm on Arch with Gnome also, and it's not working for me either.

When I run it from the command line, I see some errors on startup, but I see these errors even when I start it up using the default theme:

```
$ gimp
GEGL-geglmodule.c-Message: Module '/usr/lib/gegl-0.2/openraw.so' load error: libopenraw.so.7: cannot open shared object file: No such file or directory
/usr/lib/gimp/2.0/plug-ins/web-page: error while loading shared libraries: libwebkitgtk-1.0.so.0: cannot open shared object file: No such file or directory

(gimp:14328): LibGimpBase-WARNING **: gimp: gimp_wire_read(): error
/usr/lib/gimp/2.0/plug-ins/help-browser: error while loading shared libraries: libwebkitgtk-1.0.so.0: cannot open shared object file: No such file or directory

(gimp:14328): LibGimpBase-WARNING **: gimp: gimp_wire_read(): error
```

Nothing new gets logged when I change the theme.  Like @LucidTaZ, when I choose it something (maybe the border sizes) changes, but the icons don't.

Here's the detailed version info:

```
 $ gimp-console --version --verbose
GNU Image Manipulation Program version 2.8.18
git-describe: GIMP_2_8_16-114-gcd2bbf7

using GEGL version 0.2.0 (compiled against version 0.2.0)
using GLib version 2.50.2 (compiled against version 2.50.2)
using GdkPixbuf version 2.36.4 (compiled against version 2.36.1)
using Pango version 1.40.3 (compiled against version 1.40.3)
using Fontconfig version 2.12.1 (compiled against version 2.12.1)
using Cairo version 1.14.8 (compiled against version 1.14.8)
```

**Comment by jedireza** [comment]
Thanks for adding detail everyone. I'm time poor at the moment so please feel free to open a PR if you think you've got a solution.

**Comment by cwells** [comment]
Didn't work on Fedora 25 for me, either. Here's the fix:
```
cd ~/.gimp-2.8/themes/gimp-hidpi
mv gimp-hidpi-master/* .
rmdir gimp-hidpi-master
```
Theme should now be working.

**Comment by jedireza** [comment]
Yep. I hope it's a simple unzip mistake. In the installation instructions I'm using the `-d` option of `unzip` which extracts the files of the zip directly into the target.

**Comment by LucidTaZ** [comment]
I created a pull request for the readme that contains a fix. Note that the zip should always contain a top level directory (as it does now), but I believe GitHub always adds that.

When following the new instruction, the directory is called "gimp-hidpi-master", not "gimp-hidpi". It's not an issue for the functionality though, and it might actually be preferable.

**Comment by nwallace** [comment]
Worked for me too to get the icons in place. Thanks @cwells. However, even though the icons are SVGs, they're still small (as well as the dialogs, and toolbox, the layers window, etc). Seems more like a GIMP issue than a theme issue though. Do you all know if there's something else I could to scale things up? My monitor is 3200x1800px @ 276ppi (it's a Dell XPS 13). Don't hold up closing this issue on my account though -- like I said, this seems unrelated.

**Comment by jedireza** [comment]
Apologies for the unzip confusion here. The README has been updated accordingly.
